# Generated by Django 3.2.4 on 2021-07-21 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_alter_producto_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='fechaRegistro',
            field=models.DateField(auto_now_add=True),
        ),
    ]
