# Generated by Django 3.2.4 on 2021-08-02 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='medida',
            field=models.CharField(default='Gramos', max_length=20),
        ),
    ]
