# Generated by Django 3.2.4 on 2021-07-05 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='celular',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
