# Generated by Django 3.2.4 on 2021-07-16 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0002_alter_evento_celular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='evento',
            name='start',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='evento',
            name='updated',
            field=models.DateField(auto_now_add=True),
        ),
    ]
