# Generated by Django 3.2.4 on 2021-07-16 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0003_auto_20210715_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='updated',
            field=models.DateField(auto_now=True),
        ),
    ]
