# Generated by Django 3.2.4 on 2021-07-17 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0004_alter_evento_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='horaFinal',
            field=models.CharField(default='00:00', max_length=5),
        ),
        migrations.AddField(
            model_name='evento',
            name='horaInicio',
            field=models.CharField(default='00:00', max_length=5),
        ),
    ]
