# Generated by Django 3.2.4 on 2021-07-19 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0006_alter_evento_horainicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='horaInicio',
            field=models.CharField(max_length=5),
        ),
    ]
